[package]
name = "randomizer"
version = "0.1.0"
authors = ["Moritz Eck <moritz.eck@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = "1"

# crypto library from crypto crate
crypto = { path = "../crypto" }

[[bin]]
name = "randomizer"
path = "src/main.rs"