name: Build Docker Container

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  TZ: Europe/Zurich
  CARGO_TERM_COLOR: always

jobs:
  build-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build Image and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/bc-node/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/provotum-mixnet:latest
            ghcr.io/${{ github.repository_owner }}/provotum-mixnet:${{ github.run_id }}
