name: build + test randomizer

on:
  pull_request:
    branches: [master]
    paths:
      - "randomizer/**"
      - "!**.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: randomizer

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-crypto
      - name: Install Latest Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.50.0
          override: true
      - name: Build Randomizer
        run: cargo  build --verbose --release
      - name: Run Tests
        run: cargo test --verbose --no-fail-fast --release
