name: Security Audit
on:
  schedule:
    - cron: '0 5 * * *'
  pull_request:
    branches: [master]
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  audit_crypto_crate:
    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: crypto

    steps:
      - uses: actions/checkout@v1
      - name: install cargo-audit binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - name: audit dependencies
        run: cargo audit

  audit_bc_node:
    runs-on: ubuntu-latest
        
    defaults:
      run:
        working-directory: bc-node
        
    steps:
      - uses: actions/checkout@v1
      - name: install cargo-audit binary crate
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-audit
          version: latest
          use-tool-cache: true
      - name: audit dependencies
        run: cargo audit