name: substrate dev

on:
  pull_request:
    branches: [master]
    paths:
      - "bc-node/**"
      - "!**.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/bc-node
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-dev
      - name: Setup Unix
        run: |
          curl https://getsubstrate.io -sSf | bash -s -- --fast

      - name: Setup Rust toolchain
        run: |
          rustup default stable
          rustup toolchain install nightly-2021-01-20
          rustup target add wasm32-unknown-unknown --toolchain nightly-2021-01-20
          rustup update

      - name: Build Dev Binary
        run: cargo +nightly-2021-01-20 build --features runtime-benchmarks --verbose
        working-directory: ${{ github.workspace }}/bc-node/node

      - name: Test Dev Binary
        run: cargo +nightly-2021-01-20 test --verbose -- --nocapture

      - name: Perform Benchmark Tests
        run: cargo +nightly-2021-01-20 test -p pallet-mixnet --features runtime-benchmarks --verbose -- --nocapture
        working-directory: ${{ github.workspace }}/bc-node/node
