name: substrate production

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/bc-node
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-prod

      - name: Setup Unix
        run: |
          curl https://getsubstrate.io -sSf | bash -s -- --fast

      - name: Setup Rust toolchain
        run: |
          rustup default stable
          rustup toolchain install nightly-2020-10-06
          rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-06
          rustup update

      - name: Build Prod Binary
        run: cargo +nightly-2020-10-06 build --release --features runtime-benchmarks
        working-directory: ${{ github.workspace }}/bc-node/node

      - name: Test Prod Binary
        run: cargo +nightly-2020-10-06 test --release

      # this step uploads the built prod binary as an artifact (output)
      - name: Upload Prod Binary
        uses: actions/upload-artifact@v2
        with:
          name: provotum-prod-${{ github.sha }}-${{ github.run_id }}
          path: ${{ github.workspace }}/bc-node/target/release/provotum
          retention-days: 30

      - name: Benchmark Pallet Mixnet
        run: ${{ github.workspace }}/bc-node/target/release/provotum benchmark --chain dev --pallet "pallet_mixnet" --extrinsic "*" --repeat 2
