name: build test client

on:
  pull_request:
    branches: [master]
    paths:
      - "client/**"
      - "!**.md"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/client
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup Unix
        run: |
          curl https://getsubstrate.io -sSf | bash -s -- --fast

      - name: Setup Rust Toolchain
        run: |
          rustup default stable
          rustup toolchain install nightly-2021-01-20
          rustup update

      - name: Build Binary
        run: cargo +nightly-2021-01-20 build --release --verbose
        working-directory: ${{ github.workspace }}/client
